In [1]:
import requests
import pandas as pd
import time

In [ ]:
API_KEY = "YOUR API KEY GOES HERE!"
BASE_URL = "http://api.weatherapi.com/v1/history.json"

In [3]:
df = pd.read_csv("data/output/county_city_date_counts.csv")

In [4]:
df.head()

   BEGIN_DATE  COUNTY_NAME BEGIN_LOCATION  TOTAL_EVENTS
0  2015-04-03   ESTILL CO.        CRYSTAL             2
1  2015-04-03    FLOYD CO.        BONANZA             2
2  2015-04-03  JACKSON CO.  CLOVER BOTTOM             2
3  2015-04-03     PIKE CO.      PIKEVILLE             2
4  2015-04-03  SPENCER CO.      ELK CREEK             2

In [5]:
results = []

In [6]:
row = df.iloc[0]

city = row["BEGIN_LOCATION"]
date = row["BEGIN_DATE"]

query = f"{city}, KY"

params = {
    "key": API_KEY,
    "q": query,
    "dt": date
}

response = requests.get(BASE_URL, params=params)
data = response.json()

data

{'location': {'name': 'Crystal',
  'region': 'Kentucky',
  'country': 'United States of America',
  'lat': 37.6633,
  'lon': -83.8256,
  'tz_id': 'America/New_York',
  'localtime_epoch': 1777570803,
  'localtime': '2026-04-30 13:40'},
 'forecast': {'forecastday': [{'date': '2015-04-03',
    'date_epoch': 1428019200,
    'day': {'maxtemp_c': 18.2,
     'maxtemp_f': 64.8,
     'mintemp_c': 6.7,
     'mintemp_f': 44.1,
     'avgtemp_c': 15.0,
     'avgtemp_f': 59.1,
     'maxwind_mph': 13.2,
     'maxwind_kph': 21.2,
     'totalprecip_mm': 31.09,
     'totalprecip_in': 1.22,
     'totalsnow_cm': 0.0,
     'avgvis_km': 5.8,
     'avgvis_miles': 3.0,
     'avghumidity': 95,
     'daily_will_it_rain': 1,
     'daily_chance_of_rain': 100,
     'daily_will_it_snow': 0,
     'daily_chance_of_snow': 0,
     'condition': {'text': 'Moderate or heavy rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
      'code': 1243},
     'uv': 1.1},
    'astro': {'sunrise': '07:18 AM',
     'sunset': '08:00 PM',
     'moonrise': '07:28 PM',
     'moonset': '06:50 AM',
     'moon_phase': 'Waxing Gibbous',
     'moon_illumination': 98},
    'hour': [{'time_epoch': 1428033600,
      'time': '2015-04-03 00:00',
      'temp_c': 14.3,
      'temp_f': 57.7,
      'is_day': 0,
      'condition': {'text': 'Moderate rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/299.png',
       'code': 1186},
      'wind_mph': 8.5,
      'wind_kph': 13.7,
      'wind_degree': 234,
      'wind_dir': 'SW',
      'pressure_mb': 1013.0,
      'pressure_in': 29.92,
      'precip_mm': 0.6,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 90,
      'cloud': 63,
      'feelslike_c': 13.3,
      'feelslike_f': 56.0,
      'windchill_c': 13.3,
      'windchill_f': 56.0,
      'heatindex_c': 14.3,
      'heatindex_f': 57.7,
      'dewpoint_c': 12.8,
      'dewpoint_f': 55.0,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 31.5,
      'gust_kph': 50.6,
      'uv': 0.0},
     {'time_epoch': 1428037200,
      'time': '2015-04-03 01:00',
      'temp_c': 14.3,
      'temp_f': 57.8,
      'is_day': 0,
      'condition': {'text': 'Patchy rain possible',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/176.png',
       'code': 1063},
      'wind_mph': 8.9,
      'wind_kph': 14.4,
      'wind_degree': 228,
      'wind_dir': 'SW',
      'pressure_mb': 1013.0,
      'pressure_in': 29.91,
      'precip_mm': 0.4,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 92,
      'cloud': 72,
      'feelslike_c': 13.3,
      'feelslike_f': 56.0,
      'windchill_c': 13.3,
      'windchill_f': 56.0,
      'heatindex_c': 14.3,
      'heatindex_f': 57.8,
      'dewpoint_c': 13.2,
      'dewpoint_f': 55.7,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 7.7,
      'vis_miles': 4.0,
      'gust_mph': 25.0,
      'gust_kph': 40.3,
      'uv': 0.0},
     {'time_epoch': 1428040800,
      'time': '2015-04-03 02:00',
      'temp_c': 14.4,
      'temp_f': 57.9,
      'is_day': 0,
      'condition': {'text': 'Moderate rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/299.png',
       'code': 1186},
      'wind_mph': 9.4,
      'wind_kph': 15.1,
      'wind_degree': 222,
      'wind_dir': 'SW',
      'pressure_mb': 1013.0,
      'pressure_in': 29.91,
      'precip_mm': 0.5,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 94,
      'cloud': 81,
      'feelslike_c': 13.3,
      'feelslike_f': 55.9,
      'windchill_c': 13.3,
      'windchill_f': 55.9,
      'heatindex_c': 14.4,
      'heatindex_f': 57.9,
      'dewpoint_c': 13.5,
      'dewpoint_f': 56.4,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.3,
      'vis_miles': 3.0,
      'gust_mph': 31.0,
      'gust_kph': 50.0,
      'uv': 0.0},
     {'time_epoch': 1428044400,
      'time': '2015-04-03 03:00',
      'temp_c': 14.4,
      'temp_f': 57.9,
      'is_day': 0,
      'condition': {'text': 'Patchy rain possible',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/176.png',
       'code': 1063},
      'wind_mph': 9.8,
      'wind_kph': 15.8,
      'wind_degree': 217,
      'wind_dir': 'SW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.9,
      'precip_mm': 0.2,
      'precip_in': 0.01,
      'snow_cm': 0.0,
      'humidity': 96,
      'cloud': 91,
      'feelslike_c': 13.3,
      'feelslike_f': 55.9,
      'windchill_c': 13.3,
      'windchill_f': 55.9,
      'heatindex_c': 14.4,
      'heatindex_f': 57.9,
      'dewpoint_c': 13.9,
      'dewpoint_f': 57.0,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 3.0,
      'vis_miles': 1.0,
      'gust_mph': 30.5,
      'gust_kph': 49.1,
      'uv': 0.0},
     {'time_epoch': 1428048000,
      'time': '2015-04-03 04:00',
      'temp_c': 14.8,
      'temp_f': 58.7,
      'is_day': 0,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/356.png',
       'code': 1243},
      'wind_mph': 10.4,
      'wind_kph': 16.8,
      'wind_degree': 217,
      'wind_dir': 'SW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.9,
      'precip_mm': 1.7,
      'precip_in': 0.07,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 94,
      'feelslike_c': 13.7,
      'feelslike_f': 56.7,
      'windchill_c': 13.7,
      'windchill_f': 56.7,
      'heatindex_c': 14.8,
      'heatindex_f': 58.7,
      'dewpoint_c': 14.3,
      'dewpoint_f': 57.8,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 3.7,
      'vis_miles': 2.0,
      'gust_mph': 32.0,
      'gust_kph': 51.4,
      'uv': 0.0},
     {'time_epoch': 1428051600,
      'time': '2015-04-03 05:00',
      'temp_c': 15.3,
      'temp_f': 59.5,
      'is_day': 0,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/356.png',
       'code': 1243},
      'wind_mph': 5.5,
      'wind_kph': 8.9,
      'wind_degree': 218,
      'wind_dir': 'SW',
      'pressure_mb': 1013.0,
      'pressure_in': 29.9,
      'precip_mm': 1.8,
      'precip_in': 0.07,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 97,
      'feelslike_c': 15.3,
      'feelslike_f': 59.5,
      'windchill_c': 15.3,
      'windchill_f': 59.5,
      'heatindex_c': 15.3,
      'heatindex_f': 59.5,
      'dewpoint_c': 14.8,
      'dewpoint_f': 58.6,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 4.3,
      'vis_miles': 2.0,
      'gust_mph': 30.7,
      'gust_kph': 49.5,
      'uv': 0.0},
     {'time_epoch': 1428055200,
      'time': '2015-04-03 06:00',
      'temp_c': 15.7,
      'temp_f': 60.3,
      'is_day': 0,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/356.png',
       'code': 1243},
      'wind_mph': 3.4,
      'wind_kph': 5.4,
      'wind_degree': 219,
      'wind_dir': 'SW',
      'pressure_mb': 1013.0,
      'pressure_in': 29.9,
      'precip_mm': 3.0,
      'precip_in': 0.12,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 100,
      'feelslike_c': 15.7,
      'feelslike_f': 60.3,
      'windchill_c': 15.7,
      'windchill_f': 60.3,
      'heatindex_c': 15.7,
      'heatindex_f': 60.3,
      'dewpoint_c': 15.2,
      'dewpoint_f': 59.4,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.0,
      'vis_miles': 3.0,
      'gust_mph': 27.4,
      'gust_kph': 44.0,
      'uv': 0.0},
     {'time_epoch': 1428058800,
      'time': '2015-04-03 07:00',
      'temp_c': 15.0,
      'temp_f': 59.0,
      'is_day': 0,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/356.png',
       'code': 1243},
      'wind_mph': 4.9,
      'wind_kph': 7.9,
      'wind_degree': 215,
      'wind_dir': 'SW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.9,
      'precip_mm': 2.9,
      'precip_in': 0.11,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 100,
      'feelslike_c': 15.0,
      'feelslike_f': 59.0,
      'windchill_c': 15.0,
      'windchill_f': 59.0,
      'heatindex_c': 15.0,
      'heatindex_f': 59.0,
      'dewpoint_c': 14.8,
      'dewpoint_f': 58.6,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.0,
      'vis_miles': 3.0,
      'gust_mph': 22.3,
      'gust_kph': 35.8,
      'uv': 0.0},
     {'time_epoch': 1428062400,
      'time': '2015-04-03 08:00',
      'temp_c': 15.3,
      'temp_f': 59.5,
      'is_day': 1,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
       'code': 1243},
      'wind_mph': 6.5,
      'wind_kph': 10.4,
      'wind_degree': 212,
      'wind_dir': 'SSW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.89,
      'precip_mm': 2.8,
      'precip_in': 0.11,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 100,
      'feelslike_c': 15.3,
      'feelslike_f': 59.5,
      'windchill_c': 15.3,
      'windchill_f': 59.5,
      'heatindex_c': 15.3,
      'heatindex_f': 59.5,
      'dewpoint_c': 15.1,
      'dewpoint_f': 59.1,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.0,
      'vis_miles': 3.0,
      'gust_mph': 26.7,
      'gust_kph': 43.0,
      'uv': 0.0},
     {'time_epoch': 1428066000,
      'time': '2015-04-03 09:00',
      'temp_c': 15.7,
      'temp_f': 60.3,
      'is_day': 1,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
       'code': 1243},
      'wind_mph': 8.1,
      'wind_kph': 13.0,
      'wind_degree': 209,
      'wind_dir': 'SSW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.89,
      'precip_mm': 2.9,
      'precip_in': 0.11,
      'snow_cm': 0.0,
      'humidity': 97,
      'cloud': 100,
      'feelslike_c': 15.7,
      'feelslike_f': 60.3,
      'windchill_c': 15.7,
      'windchill_f': 60.3,
      'heatindex_c': 15.7,
      'heatindex_f': 60.3,
      'dewpoint_c': 15.4,
      'dewpoint_f': 59.8,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.0,
      'vis_miles': 3.0,
      'gust_mph': 36.2,
      'gust_kph': 58.3,
      'uv': 0.0},
     {'time_epoch': 1428069600,
      'time': '2015-04-03 10:00',
      'temp_c': 16.2,
      'temp_f': 61.2,
      'is_day': 1,
      'condition': {'text': 'Moderate rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/299.png',
       'code': 1186},
      'wind_mph': 5.5,
      'wind_kph': 8.8,
      'wind_degree': 213,
      'wind_dir': 'SW',
      'pressure_mb': 1012.0,
      'pressure_in': 29.87,
      'precip_mm': 0.8,
      'precip_in': 0.03,
      'snow_cm': 0.0,
      'humidity': 96,
      'cloud': 99,
      'feelslike_c': 16.3,
      'feelslike_f': 61.3,
      'windchill_c': 16.2,
      'windchill_f': 61.2,
      'heatindex_c': 16.2,
      'heatindex_f': 61.2,
      'dewpoint_c': 15.9,
      'dewpoint_f': 60.6,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.3,
      'vis_miles': 3.0,
      'gust_mph': 29.5,
      'gust_kph': 47.5,
      'uv': 0.1},
     {'time_epoch': 1428073200,
      'time': '2015-04-03 11:00',
      'temp_c': 17.8,
      'temp_f': 64.0,
      'is_day': 1,
      'condition': {'text': 'Patchy rain possible',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
       'code': 1063},
      'wind_mph': 7.6,
      'wind_kph': 12.2,
      'wind_degree': 218,
      'wind_dir': 'SW',
      'pressure_mb': 1011.0,
      'pressure_in': 29.85,
      'precip_mm': 0.3,
      'precip_in': 0.01,
      'snow_cm': 0.0,
      'humidity': 96,
      'cloud': 99,
      'feelslike_c': 17.8,
      'feelslike_f': 64.0,
      'windchill_c': 17.8,
      'windchill_f': 64.0,
      'heatindex_c': 17.8,
      'heatindex_f': 64.0,
      'dewpoint_c': 17.1,
      'dewpoint_f': 62.8,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.7,
      'vis_miles': 3.0,
      'gust_mph': 30.4,
      'gust_kph': 49.0,
      'uv': 0.4},
     {'time_epoch': 1428076800,
      'time': '2015-04-03 12:00',
      'temp_c': 18.2,
      'temp_f': 64.8,
      'is_day': 1,
      'condition': {'text': 'Heavy rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/305.png',
       'code': 1192},
      'wind_mph': 7.4,
      'wind_kph': 11.9,
      'wind_degree': 222,
      'wind_dir': 'SW',
      'pressure_mb': 1010.0,
      'pressure_in': 29.83,
      'precip_mm': 1.29,
      'precip_in': 0.05,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 98,
      'feelslike_c': 18.2,
      'feelslike_f': 64.8,
      'windchill_c': 18.2,
      'windchill_f': 64.8,
      'heatindex_c': 18.2,
      'heatindex_f': 64.8,
      'dewpoint_c': 17.4,
      'dewpoint_f': 63.3,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 6.0,
      'vis_miles': 3.0,
      'gust_mph': 28.4,
      'gust_kph': 45.8,
      'uv': 0.7},
     {'time_epoch': 1428080400,
      'time': '2015-04-03 13:00',
      'temp_c': 18.2,
      'temp_f': 64.8,
      'is_day': 1,
      'condition': {'text': 'Heavy rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/305.png',
       'code': 1192},
      'wind_mph': 8.7,
      'wind_kph': 14.0,
      'wind_degree': 226,
      'wind_dir': 'SW',
      'pressure_mb': 1010.0,
      'pressure_in': 29.81,
      'precip_mm': 1.2,
      'precip_in': 0.05,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 96,
      'feelslike_c': 18.2,
      'feelslike_f': 64.8,
      'windchill_c': 18.2,
      'windchill_f': 64.8,
      'heatindex_c': 18.2,
      'heatindex_f': 64.8,
      'dewpoint_c': 17.4,
      'dewpoint_f': 63.3,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 6.0,
      'vis_miles': 3.0,
      'gust_mph': 31.2,
      'gust_kph': 50.2,
      'uv': 1.0},
     {'time_epoch': 1428084000,
      'time': '2015-04-03 14:00',
      'temp_c': 18.2,
      'temp_f': 64.8,
      'is_day': 1,
      'condition': {'text': 'Heavy rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/305.png',
       'code': 1192},
      'wind_mph': 7.7,
      'wind_kph': 12.4,
      'wind_degree': 229,
      'wind_dir': 'SW',
      'pressure_mb': 1009.0,
      'pressure_in': 29.79,
      'precip_mm': 1.0,
      'precip_in': 0.04,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 94,
      'feelslike_c': 18.2,
      'feelslike_f': 64.8,
      'windchill_c': 18.2,
      'windchill_f': 64.8,
      'heatindex_c': 18.2,
      'heatindex_f': 64.8,
      'dewpoint_c': 17.3,
      'dewpoint_f': 63.2,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 6.0,
      'vis_miles': 3.0,
      'gust_mph': 18.4,
      'gust_kph': 29.5,
      'uv': 1.1},
     {'time_epoch': 1428087600,
      'time': '2015-04-03 15:00',
      'temp_c': 18.2,
      'temp_f': 64.8,
      'is_day': 1,
      'condition': {'text': 'Patchy rain possible',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
       'code': 1063},
      'wind_mph': 11.4,
      'wind_kph': 18.4,
      'wind_degree': 233,
      'wind_dir': 'SW',
      'pressure_mb': 1008.0,
      'pressure_in': 29.78,
      'precip_mm': 0.2,
      'precip_in': 0.01,
      'snow_cm': 0.0,
      'humidity': 94,
      'cloud': 92,
      'feelslike_c': 18.2,
      'feelslike_f': 64.8,
      'windchill_c': 18.2,
      'windchill_f': 64.8,
      'heatindex_c': 18.2,
      'heatindex_f': 64.8,
      'dewpoint_c': 17.3,
      'dewpoint_f': 63.1,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 6.0,
      'vis_miles': 3.0,
      'gust_mph': 26.3,
      'gust_kph': 42.3,
      'uv': 0.9},
     {'time_epoch': 1428091200,
      'time': '2015-04-03 16:00',
      'temp_c': 17.8,
      'temp_f': 64.1,
      'is_day': 1,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
       'code': 1243},
      'wind_mph': 10.2,
      'wind_kph': 16.4,
      'wind_degree': 251,
      'wind_dir': 'WSW',
      'pressure_mb': 1009.0,
      'pressure_in': 29.78,
      'precip_mm': 1.6,
      'precip_in': 0.06,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 95,
      'feelslike_c': 17.8,
      'feelslike_f': 64.1,
      'windchill_c': 17.8,
      'windchill_f': 64.1,
      'heatindex_c': 17.8,
      'heatindex_f': 64.1,
      'dewpoint_c': 17.0,
      'dewpoint_f': 62.7,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 5.0,
      'vis_miles': 3.0,
      'gust_mph': 28.3,
      'gust_kph': 45.5,
      'uv': 0.5},
     {'time_epoch': 1428094800,
      'time': '2015-04-03 17:00',
      'temp_c': 17.5,
      'temp_f': 63.4,
      'is_day': 1,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
       'code': 1243},
      'wind_mph': 9.0,
      'wind_kph': 14.5,
      'wind_degree': 269,
      'wind_dir': 'W',
      'pressure_mb': 1009.0,
      'pressure_in': 29.79,
      'precip_mm': 1.5,
      'precip_in': 0.06,
      'snow_cm': 0.0,
      'humidity': 96,
      'cloud': 97,
      'feelslike_c': 17.5,
      'feelslike_f': 63.4,
      'windchill_c': 17.5,
      'windchill_f': 63.4,
      'heatindex_c': 17.5,
      'heatindex_f': 63.4,
      'dewpoint_c': 16.8,
      'dewpoint_f': 62.2,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 4.0,
      'vis_miles': 2.0,
      'gust_mph': 30.8,
      'gust_kph': 49.5,
      'uv': 0.2},
     {'time_epoch': 1428098400,
      'time': '2015-04-03 18:00',
      'temp_c': 17.1,
      'temp_f': 62.8,
      'is_day': 1,
      'condition': {'text': 'Heavy rain at times',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/305.png',
       'code': 1192},
      'wind_mph': 7.8,
      'wind_kph': 12.6,
      'wind_degree': 287,
      'wind_dir': 'WNW',
      'pressure_mb': 1009.0,
      'pressure_in': 29.8,
      'precip_mm': 1.2,
      'precip_in': 0.05,
      'snow_cm': 0.0,
      'humidity': 96,
      'cloud': 100,
      'feelslike_c': 17.1,
      'feelslike_f': 62.8,
      'windchill_c': 17.1,
      'windchill_f': 62.8,
      'heatindex_c': 17.1,
      'heatindex_f': 62.8,
      'dewpoint_c': 16.5,
      'dewpoint_f': 61.7,
      'will_it_rain': 1,
      'chance_of_rain': 100,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 3.0,
      'vis_miles': 1.0,
      'gust_mph': 35.2,
      'gust_kph': 56.7,
      'uv': 0.0},
     {'time_epoch': 1428102000,
      'time': '2015-04-03 19:00',
      'temp_c': 15.4,
      'temp_f': 59.8,
      'is_day': 1,
      'condition': {'text': 'Moderate or heavy rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/356.png',
       'code': 1243},
      'wind_mph': 8.9,
      'wind_kph': 14.4,
      'wind_degree': 302,
      'wind_dir': 'WNW',
      'pressure_mb': 1009.0,

In [7]:
day = data["forecast"]["forecastday"][0]["day"]

print(day["avgtemp_f"])
print(day["maxtemp_f"])
print(day["mintemp_f"])
print(day["condition"]["text"])

59.1
64.8
44.1
Moderate or heavy rain shower

In [8]:
for index, row in df.iterrows():
    
    city = row["BEGIN_LOCATION"]
    county = row["COUNTY_NAME"]
    date = row["BEGIN_DATE"]

    query = f"{city}, KY"

    params = {
        "key": API_KEY,
        "q": query,
        "dt": date
    }

    try:
        response = requests.get(BASE_URL, params=params)
        data = response.json()

        day = data["forecast"]["forecastday"][0]["day"]

        results.append({
            "BEGIN_DATE": date,
            "COUNTY_NAME": county,
            "BEGIN_LOCATION": city,
            "avg_temp_f": day["avgtemp_f"],
            "max_temp_f": day["maxtemp_f"],
            "min_temp_f": day["mintemp_f"],
            "precip_in": day["totalprecip_in"],
            "condition": day["condition"]["text"]
        })

        print("Success:", city)

    except:
        print("Failed:", city)

    time.sleep(1)

Success: CRYSTAL
Success: BONANZA
Success: CLOVER BOTTOM
Success: PIKEVILLE
Success: ELK CREEK
Success: LAWRENCEBURG
Success: OWINGSVILLE
Success: SALT LICK
Success: LAWSON
Success: OAKDALE
Success: HARDINSBURG ARPT
Success: BARRALLTON
Success: BRUIN
Success: IRVINE
Success: NORTH IRVINE
Success: PRYSE
Success: LEXINGTON
Success: PRESTONSBURG
Success: RISNER
Success: PEAKS MILL
Success: (LOU)BOWMAN FLD LOUI
Success: AUDUBON PARK
Success: LOUISVILLE
Success: NEWBURG
Success: PLEASURE RIDGE PARK
Success: SMYRNA
Success: MOUSIE
Success: WEBBVILLE
Success: PRIMROSE
Success: WAYNESBURG
Success: WHITE HALL
Success: FORAKER
Success: HAYSVILLE
Success: EWINGTON
Success: MT STERLING
Success: BELLS RUN
Success: CENTERFIELD
Success: BOONEVILLE
Success: KIMPER
Success: NATURAL BRIDGE
Success: WALTERSVILLE
Success: MOREHEAD
Success: SHELBYVILLE
Success: MONITOR
Success: BETHANY
Success: LEE CITY
Success: MIRACLE
Success: HINDMAN
Success: WEST LIBERTY
Success: HISLE
Success: AVENSTOKE
Success: CALVIN
Success: CUBAGE
Success: JACKSON
Success: KECK
Success: QUICKSAND
Success: SEWELL
Success: CARROLLTON
Success: ENGLISH
Success: SMITHS CREEK
Success: MANTON
Success: WARCO
Success: CAMPBELLSBURG
Success: SULPHUR
Success: AUDUBON PARK
Success: ST REGIS PARK
Success: WORTHINGTON
Success: WILMORE
Success: RITCHIE
Success: BARBOURVILLE
Success: JARVIS
Success: SPRULE
Success: EAST BERNSTADT
Success: WEBBVILLE
Success: BEAR BRANCH
Success: THOUSANDSTICKS
Success: LETCHER
Success: LOGVILLE
Success: SALYERSVILLE
Success: GILREATH
Success: FRENCHBURG
Success: MARIBA
Success: NEVADA
Success: INDEX
Success: BLOOMFIELD
Success: STURGEON
Success: DWARF
Success: SOMERSET
Success: CONWAY
Success: ELK CREEK
Success: TAYLORSVILLE
Success: MONITOR
Success: TROUT
Success: OIL VLY
Success: CAMPTON
Success: HAZEL GREEN
Success: MILLTOWN
Success: MAYNARD
Success: PAXTON
Success: MONFORD
Success: LYNN GROVE
Success: WINDSOR
Success: WAGO
Success: AMANDAVILLE
Success: HUFF
Success: WINDYVILLE
Success: PRESTONSBURG
Success: CARTERSVILLE
Success: SHORT CREEK
Success: GRESHAM
Success: PERRYVILLE
Success: CLINTON
Success: DAWKINS
Success: BUFFALO
Success: OLD LNDG
Success: CHICKEN BRISTLE
Success: DANBY
Success: LEWISBURG
Success: UNION CITY
Success: FALCON
Success: SALYERSVILLE
Success: DEBORD
Success: ESTES
Success: OTIA
Success: BURG
Success: MIZE
Success: HARTFORD
Success: WHITTLE
Success: FRANKLIN
Success: MIDDLETON
Success: HOBSON
Success: TRENTON
Success: CADIZ
Success: BOWLING GREEN
Success: BETHANY
Success: CAMPTON
Success: LEE CITY
Success: MT WASHINGTON
Success: CORDOVA
Success: SKAGGSTOWN
Success: MULDRAUGH
Success: FOUR OAKS
Success: ELIZABETH STATION
Success: MILFORD
Success: FAIRFIELD
Success: HIGH PLAINS
Success: BROOKS
Success: HUBERS
Success: BOSTON
Success: POTTERTOWN
Success: PEEDEE
Success: VILEY
Success: DOWINGSVILLE
Success: MEREDITH
Success: PEONIA
Success: EASTVIEW
Success: GAITHERS
Success: TUNNEL HILL
Success: SYLVANDELL
Success: BECKLEY
Success: HIGHVIEW
Success: SMYRNA
Success: CENTRAL CITY
Success: BLOOMFIELD
Success: NELSONVILLE
Success: BEAVER DAM
Success: TAYLOR MINES
Success: GRATZ
Success: TACKETTS MILL
Success: MARCUS
Success: PIQUA
Success: ELK CREEK
Success: TRIGG FURNACE
Success: BROWNING
Success: MURRAY
Success: ELMWOOD
Success: COLUMBIA
Success: PORTLAND
Success: SCOTTSVILLE
Success: GAGE
Success: CEDAR BLUFF
Success: ALMO
Success: LYNN GROVE
Success: NEW CONCORD
Success: ARLINGTON
Success: CUNNINGHAM
Success: MILBURN
Success: LIBERTY
Success: GAINSVILLE
Success: PEMBROKE
Success: FRANCES
Success: NEW SALEM
Success: DOUGAN TOWN
Success: PETTIT
Success: ANNA LYNNE
Success: CAYCE
Success: BALTIMORE
Success: HOLIFIELD
Success: VIOLA
Success: GLENDALE JCT
Success: BONNIEVILLE
Success: BEULAH
Success: CROLEY
Success: WATTS
Success: NEBO
Success: NORTONVILLE
Success: COOPERSTOWN
Success: KUTTAWA
Success: BENTON
Success: BREWERS
Success: KREBS
Success: OAKS
Success: WRIGHTBURG
Success: FLIPPIN
Success: CENTRAL CITY
Success: BEAVER DAM
Success: HORTON
Success: JINGO
Success: CRESTWOOD
Success: PEWEE VLY
Success: LONGLICK
Success: SADIEVILLE
Success: BLACK JACK
Success: FRANKLIN
Success: FRANKLIN WHAK ARPT
Success: GUTHRIE
Success: CERULEAN
Success: ROARING SPG
Success: BOWLING GREEN
Success: BROWNING
Success: COHRON
Success: CLAY
Success: LUZON

In [9]:
weather_df = pd.DataFrame(results)
weather_df.head()

,BEGIN_DATE,COUNTY_NAME,BEGIN_LOCATION,avg_temp_f,max_temp_f,min_temp_f,precip_in,condition
0,2015-04-03,ESTILL CO.,CRYSTAL,59.1,64.8,44.1,1.22,Moderate or heavy rain shower
1,2015-04-03,FLOYD CO.,BONANZA,61.2,68.3,48.3,1.31,Moderate or heavy rain shower
2,2015-04-03,JACKSON CO.,CLOVER BOTTOM,60.0,68.0,46.3,1.06,Moderate or heavy rain shower
3,2015-04-03,PIKE CO.,PIKEVILLE,61.7,70.0,50.9,0.93,Moderate or heavy rain shower
4,2015-04-03,SPENCER CO.,ELK CREEK,58.7,65.5,45.0,2.65,Moderate or heavy rain shower

In [10]:
weather_df.to_csv("data/output/kentucky_weather_top_five_dates.csv", index=False)